### PR TITLE
Allow custom theme settings

### PR DESCRIPTION
**Pull request by taptapdan**
In support of work for the Figure fix in triton, I'm creating some components in perts-ui. Those are relying a breakpoints for media queries. Our different apps have different breakpoints. So need a way to specify those with our perts-ui use. This allows that. Added a storybook story to provide an example of how it works.

There's more work incoming. But I wanted to separate this out into a smaller pr since it touches a lot of files.

### CODE REVIEW

**Comment by taptapdan** [comment]
Can you suggest tests that you feel would be helpful? I've been setting up Storybook stories for the perts-ui components. I'd love to get coverage in jest/cypress if there are cases you can come up with. Thanks.

**Comment by chris-perts** [comment]
I think "doesn't crash" tests for each exported component would be a big step forward. They could all have a `data-test="ComponentName"` and jest could just mount them and check for that element.

**Comment by chris-perts** [comment]
Sorry, was interrupted, final thought: that kind of test would catch basic errors that might happen with this PR, like some component isn't wrapped in a `ThemeProvider` so when you access `props.theme.colors` it crashes.

**Comment by taptapdan** [comment]
Good idea on the not crashing tests.

---

To clarify, `ThemeProvider` isn't required to be wrapped. The change I made,

```
import theme from 'theme';

const Component = styled.div`
  some-css-rule: ${props => props.theme.someThemeProp};
`;

Component.defaultProps = {
  theme,
};
```

Allows us to fall back on the default theme settings in perts-ui. But when there is a theme, it's provided by ThemeProvider and comes in a props.theme, so it will override the default props.

**Pull request merged**
